#!/usr/bin/env bash
OWN_DIR=$(dirname "${BASH_SOURCE[0]}")
LOCATION=$(cat $OWN_DIR/*.txt | fzf | xargs -I{} grep -n '{}' $OWN_DIR/*.txt | sed 's/^\([^:]*\):\([0-9]*\):.*/+\2 \1/')
$EDITOR $LOCATION -c 'normal zz'
